#!/usr/bin/env bash

#ddev-generated
# Support for TablePro, https://tablepro.app/
# This command is available on macOS if TablePro is installed in the default location.
## Description: Run tableplus with current project database
## Usage: tablepro
## Example: "ddev tablepro"
## OSTypes: darwin
## HostBinaryExists: /Applications/TablePro.app

if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
  echo "Project ${DDEV_PROJECT} is not running, starting it"
  ddev start
  start_exit_code=$?
  if [ $start_exit_code -ne 0 ]; then
    exit $start_exit_code
  fi
  # run this script again, as the environment is updated after "ddev start"
  no_recursion=true ddev "$(basename "$0")" "$@"
  exit $?
fi

dbtype=${DDEV_DBIMAGE%:*}
driver=mysql
if [[ $dbtype == "postgres" ]]; then
  driver=$dbtype
fi
query="${driver}://db:db@127.0.0.1:${DDEV_HOST_DB_PORT}/db?Enviroment=local&Name=ddev-${DDEV_SITENAME}"

open "$query" -a "/Applications/TablePro.app/Contents/MacOS/TablePro"
